# ===============================
# SERVER
# ===============================
server.port=${PORT:8080}
server.address=0.0.0.0

# ===============================
# DATABASE (TiDB Cloud)
# ===============================
spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.alicloud.tidbcloud.com:4000/productdb?useSSL=true&requireSSL=true&verifyServerCertificate=false&serverTimezone=UTC&characterEncoding=UTF-8

spring.datasource.username=3bHkymPEJCjsZFm.root
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ===============================
# CORS
# ===============================
app.cors.allowed-origins=http://localhost:3000,https://recommender-shop-fe.vercel.app

# ===============================
# FRONTEND URL (FOR EMAIL RESET LINK)
# ===============================
app.frontend.url=https://recommender-shop-fe.vercel.app

# ===============================
# BREVO API (EMAIL SENDING)
# ===============================
brevo.api.key=${BREVO_API_KEY}
app.mail.sender.name=Recommender Shop
app.mail.sender.email=${MAIL_SENDER}
# ===============================
# SESSION COOKIE
# ===============================
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true

# ===============================
# CLOUDINARY
# ===============================
cloudinary.cloud_name=dxohrnltp
cloudinary.api_key=344522685253558
cloudinary.api_secret=${CLOUDINARY_API_SECRET}