# ===============================
# SERVER
# ===============================
server.port=${PORT:8080}
server.address=0.0.0.0

# ===============================
# DATABASE (TiDB Cloud)
# ===============================
spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.alicloud.tidbcloud.com:4000/productdb?useSSL=true&requireSSL=true&verifyServerCertificate=false&serverTimezone=UTC&characterEncoding=UTF-8

spring.datasource.username=3bHkymPEJCjsZFm.root
spring.datasource.password=Tv8VyWHPU0V5gH2b

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true

# ===============================
# CORS
# ===============================
app.cors.allowed-origins=http://localhost:3000,https://recommender-shop-fe.vercel.app

# ===============================
# FRONTEND URL (FOR EMAIL)
# ===============================
app.frontend.url=https://recommender-shop-fe.vercel.app

# ===============================
# EMAIL (SMTP)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tatbara2@gmail.com
spring.mail.password=kyrtkjslaakszzic
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# ===============================
# SESSION COOKIE (CROSS SITE)
# ===============================
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true

# ===============================
# CLOUDINARY
# ===============================
cloudinary.cloud_name=dxohrnltp
cloudinary.api_key=344522685253558
cloudinary.api_secret=KLswCcnPe3IHjCGi5LOeN1d0UE4